apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-tasks-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brain-tasks-app
  template:
    metadata:
      labels:
        app: brain-tasks-app
    spec:
      containers:
        - name: brain-tasks-app
          image: 553022076715.dkr.ecr.us-east-1.amazonaws.com/dev/mindtrack:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ecr-creds
