apiVersion: v1
kind: Service
metadata:
  name: brain-tasks-app-service
spec:
  type: LoadBalancer
  selector:
    app: brain-tasks-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80

